/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRedirectRouteImport } from './routes/auth-redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTrendingRouteImport } from './routes/_authenticated/trending'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as LoginSsoCallbackRouteImport } from './routes/login.sso-callback'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as RegisterSsoCallbackRouteImport } from './routes/register.sso-callback'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedTagTagRouteImport } from './routes/_authenticated/tag.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth-redirect',
  path: '/auth-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrendingRoute = AuthenticatedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LoginRoute,
} as any)
const LoginSsoCallbackRoute = LoginSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => LoginRoute,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSsoCallbackRoute = RegisterSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => RegisterRoute,
} as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTagTagRoute = AuthenticatedTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/admin/login': typeof AdminLoginRoute
  '/login/$': typeof LoginSplatRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/$': typeof RegisterSplatRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/tag/$tag': typeof AuthenticatedTagTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trending': typeof AuthenticatedTrendingRoute
  '/admin/login': typeof AdminLoginRoute
  '/login/$': typeof LoginSplatRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/$': typeof RegisterSplatRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/tag/$tag': typeof AuthenticatedTagTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-redirect': typeof AuthRedirectRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/sso-callback': typeof SsoCallbackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trending': typeof AuthenticatedTrendingRoute
  '/admin/login': typeof AdminLoginRoute
  '/login/$': typeof LoginSplatRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/register/$': typeof RegisterSplatRoute
  '/register/sso-callback': typeof RegisterSsoCallbackRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/tag/$tag': typeof AuthenticatedTagTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-redirect'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/trending'
    | '/admin/login'
    | '/login/$'
    | '/login/sso-callback'
    | '/register/$'
    | '/register/sso-callback'
    | '/profile/$username'
    | '/tag/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-redirect'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/admin'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/trending'
    | '/admin/login'
    | '/login/$'
    | '/login/sso-callback'
    | '/register/$'
    | '/register/sso-callback'
    | '/profile/$username'
    | '/tag/$tag'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth-redirect'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/home'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/trending'
    | '/admin/login'
    | '/login/$'
    | '/login/sso-callback'
    | '/register/$'
    | '/register/sso-callback'
    | '/_authenticated/profile/$username'
    | '/_authenticated/tag/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRedirectRoute: typeof AuthRedirectRoute
  LoginRoute: typeof LoginRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
  SsoCallbackRoute: typeof SsoCallbackRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-redirect': {
      id: '/auth-redirect'
      path: '/auth-redirect'
      fullPath: '/auth-redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trending': {
      id: '/_authenticated/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof AuthenticatedTrendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/sso-callback': {
      id: '/login/sso-callback'
      path: '/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof LoginSsoCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/register/$': {
      id: '/register/$'
      path: '/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/sso-callback': {
      id: '/register/sso-callback'
      path: '/sso-callback'
      fullPath: '/register/sso-callback'
      preLoaderRoute: typeof RegisterSsoCallbackRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tag/$tag': {
      id: '/_authenticated/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof AuthenticatedTagTagRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrendingRoute: typeof AuthenticatedTrendingRoute
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
  AuthenticatedTagTagRoute: typeof AuthenticatedTagTagRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrendingRoute: AuthenticatedTrendingRoute,
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
  AuthenticatedTagTagRoute: AuthenticatedTagTagRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LoginRouteChildren {
  LoginSplatRoute: typeof LoginSplatRoute
  LoginSsoCallbackRoute: typeof LoginSsoCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSplatRoute: LoginSplatRoute,
  LoginSsoCallbackRoute: LoginSsoCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface RegisterRouteChildren {
  RegisterSplatRoute: typeof RegisterSplatRoute
  RegisterSsoCallbackRoute: typeof RegisterSsoCallbackRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterSplatRoute: RegisterSplatRoute,
  RegisterSsoCallbackRoute: RegisterSsoCallbackRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRedirectRoute: AuthRedirectRoute,
  LoginRoute: LoginRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
  SsoCallbackRoute: SsoCallbackRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
